---

# (c) Wong Hoi Sing Edison <hswong3i@pantarei-design.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

namespace: alvistack
name: docker-python
description: Docker Image Packaging for Python

version: MAJOR.MINOR.PATCH
readme: README.md
license: Apache-2.0

repository: https://github.com/alvistack/docker-python
documentation: https://github.com/alvistack/docker-python
homepage: https://github.com/alvistack/docker-python
issues: https://github.com/alvistack/docker-python/issues

dependencies: {}
tags:
  - system
authors:
  - Wong Hoi Sing Edison <hswong3i@pantarei-design.com>
